---
- hosts: all
  become: yes
  tasks:
    - name: i want to install webserver in ansible nodes
      apt:
        name: apache2
        state: present

    - name: I want to start server
      service:
        name: apache2
        state: started
